import { Product } from './types';

export const CATEGORIES = [
  { id: 'mithai', label: 'Mithai' },
  { id: 'cakes', label: 'Cakes' },
  { id: 'dry-fruits', label: 'Dry Fruits' },
  { id: 'hampers', label: 'Hampers' },
  { id: 'snacks', label: 'Snacks' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'kaju-katli',
    name: 'Shahi Kaju Katli',
    description: '500g | 100% Pure Cashew',
    price: 640,
    unit: '500g',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOzdOmvR87bu9EIOSppArrOwikAVTAFDoDxlH77CUM8_LCjyhkrZKKDTaYpvXsJzB92CEToejocya7FOsdnlM26FZn6qmUOvGbtRkLZ485u71i8YrN8l_FJslFenIN1d702Z4tHQ5JGr88nngFmjoA0EeS2olxiu-eJf79-36FJpE8Z5X5aFNeNoOglsMY5ggxtKGXlH4k6jt4r_Pzce0Middqn_Sm3jTlpbGZZNJLLBM-XRjaAR_xHfyMoeZZxRzXREwrmG_-IaQ',
    category: 'mithai',
    tags: ['Bestseller'],
  },
  {
    id: 'saffron-rajbhog',
    name: 'Saffron Rajbhog',
    description: 'Pack of 6 | Kashmiri Saffron',
    price: 450,
    unit: 'Pack of 6',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAvNVwNs_vAs36ljUCVhH1tFnEyHpFeUufhKup03N3oITz6ZlehmG5K2Egg4ATiGxHH5XgK8462kiJl5sSEMaf4WAsFBMFRMr35wM14gavUL_M2YejPPreuuLQs0FpzYp2sfHQIqyHntLaCFOxv7HaMaFIzqp7Z5TqDRRVa-k4NTi-wd9WuiPp5NbbGBmNCnTw1SujY_mRnG0ht1CJ5LMBhZOxSPeSg1ymME7c1UGOAO7MSzDquUV_JhltCUIK2lqdwKUx1ZlUZGFs',
    category: 'mithai',
    tags: ['Premium'],
  },
  {
    id: 'dry-fruit-mix',
    name: 'Royal Dry Fruit Mix',
    description: '250g | Californian Almonds',
    price: 890,
    unit: '250g',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8Dn6y_vwCvLozCCYFbv1x7igzEh48B7Q20VXDZakTmuW5lB3B8O-RqeZwl32wyKHRdNfWqB_COWJiUMfpALcDfXR-3Vhh4OxzF-1NknmxzVVFOjniSeiXUmcjIKAThbzRYoousxnxwaFW4kxSD29bYNDBpIwWYUdhRpYvG-PSLsybzhMQmFyR05GWLIsmhkR1DMDyE7KDs40aL4ulfNA26VWjm1tk2MlNSg1302EB3NJ7jwXvQ0PFl2aYDMXA5cnvNM_Tv6grl5I',
    category: 'dry-fruits',
    tags: ['New'],
  },
  {
    id: 'utsav-hamper',
    name: 'Utsav Gift Hamper',
    description: '1.2kg | Assorted Delights',
    price: 1450,
    unit: '1.2kg',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC0CN_3xZ87a3jgSL-B2AZv2bt3N-Y5QB7udTIJb_3-fABwrQg7JzAxzXrRWRpHTWwBLr_Qi13IChCfIYSaFipzvDPNlllCK6A0mvHDydVqo_mmwFXZ2QBgdhjWSwLJVwEchBqcuO1_VDiZmunAZwUTmJdFwggB82I96iOzdCnFTrVtm7lwspPhxQMKZVMGgOqSGT3L6egV_klnmBfZUwU77djMcaw7mTnFz_aqa4mbBIzDCEL5I-8VKrXQq7-Ory__LRly-SeYZF4',
    category: 'hampers',
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    description: 'Pack of 12 | Desi Ghee',
    price: 380,
    unit: 'Pack of 12',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCL3p77ck2F3O4Tnp1i05nl-58N7ajoUvSxDVmsUxcqa7CS1Ex9qZioe2nLSi3d2omqGoGdEknB0OxVxxf-U6e0rUzQUPQGZvYHN8EW0d7U4kSj34_yJWNuNjZ6IA8FwStWW8xdfryAk6lRz3V4zpRcSUuTqw6g7NnYc-vbGxZnp1t_URZoMZ2n2E520WdukH98cqh2YJKXUVN6xE4DAx_jwY6BkMyVc8CDPNdHcG6iwC24dteISv_EsxfQCyCbnreltPL9p6RkfQs',
    category: 'mithai',
  },
  {
    id: 'kesar-rasmalai',
    name: 'Kesar Rasmalai',
    description: 'Pack of 4 | Fresh Paneer',
    price: 280,
    unit: 'Pack of 4',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCthILhOrJMRr7rJ0uZoebUObnfL0uu12gyIONSmYabL66j10PCYlA_0hZeh2wafJPsLvuKJrNSOyCamTvNi-1RqbGEf25PFjVLkgklsCznL0yYIa_9Ozd7JtiwTA6DlObUDeUYUZMr911K8s2mnR2VPgR7GZuHByLzsFsgpmIXu_MjsKl4vFgBcqbamxzZD9bka7SVXgPJ0vpCEOiaMIHQ6-PkeaAVOy73Pa6PQ6nao7U2V86omc48gPV1qP6kzB2rhDc9Mw6m5U4',
    category: 'mithai',
  },
  {
    id: 'mathura-peda',
    name: 'Heritage Mathura Peda',
    description: '500g | Slow-cooked Khoya & Cardamom',
    price: 380,
    unit: '500g',
    image: 'https://picsum.photos/seed/peda/600/600',
    category: 'mithai',
    tags: ['Traditional'],
  },
  {
    id: 'motichoor-laddoo',
    name: 'Motichoor Laddoo',
    description: '500g | Fine Gram Flour in Desi Ghee',
    price: 450,
    unit: '500g',
    image: 'https://picsum.photos/seed/laddu/600/600',
    category: 'mithai',
    tags: ['Bestseller'],
  },
  {
    id: 'dodha-barfi',
    name: 'Heritage Dodha Barfi',
    description: '500g | Sprouted Wheat & Caramelized Milk',
    price: 520,
    unit: '500g',
    image: 'https://picsum.photos/seed/burfi/600/600',
    category: 'mithai',
    tags: ['Royal'],
  },
  {
    id: 'mini-rasgulla',
    name: 'Saffron Mini Rasgulla',
    description: '500g | Spongy Cheese Balls in Saffron Syrup',
    price: 340,
    unit: '500g',
    image: 'https://picsum.photos/seed/rasgulla/600/600',
    category: 'mithai',
  },
];
